_target_: app.annotator.Annotator

defaults:
  - transform: default.yaml

net:
  _target_: src.models.components.simple_resnet.SimpleResnet
  model_name: "resnet18"
  weights: "DEFAULT"
  output_shape: [68, 2]

ckpt_path:  F:\project\facial_landmarks-wandb\logs\train\runs\2023-04-06_02-25-27\checkpoints\epoch_091.ckpt #checkout first, interpolation later
dimension: [224, 224]
